--- #YAML:1.0
name:                   WWW-UsePerl-Journal
version:                0.22
abstract:               Handles the retrieval of UsePerl journal entries.
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  LWP::UserAgent:       0
  Test::More:           0.67
  Time::Piece:          1.07
recommends:
  Test::More:           0.67
  Test::Pod:            1.00
  Test::Pod::Coverage:  1.08
  Test::CPAN::Meta:     0.12
build_requires:
  Test::More:           0.67

provides:
  WWW::UsePerl::Journal:
    file:     lib/WWW/UsePerl/Journal.pm
    version:  0.22
  WWW::UsePerl::Journal::Entry:
    file:     lib/WWW/UsePerl/Journal/Entry.pm
    version:  0.22
  WWW::UsePerl::Journal::Post:
    file:     lib/WWW/UsePerl/Journal/Post.pm
    version:  0.22
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
