# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-UsePerl-Journal
version:      0.14
version_from: lib/WWW/UsePerl/Journal.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    Test::More:                    0
    Test::Simple:                  0.4
    Time::Piece:                   1.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
